#include "timer.h"
#include "peripheral.h"
#include "clock.h"
#include "nvic.h"
#include <stddef.h>

static callback_t tim2_callback = NULL;
static void *tim2_callback_arg = NULL;

status_t timer_init(const timer_config_t *config)
{
    if (!config || !config->timer) return STATUS_INVALID_PARAM;
    
    TIM_TypeDef *tim = config->timer;
    
    /* 1. Enable Clock */
    status_t st = peripheral_enable_clock(tim);
    if (st != STATUS_OK) return st;
    
    /* 2. Calculate Prescaler */
    uint32_t timer_clk;
    if (tim == TIM2) {
        /* TIM2 is on APB1. Timer clock is PCLK1 * 2 because APB1 prescaler is 4 (!= 1) */
        timer_clk = clock_get_pclk1() * 2;
    } else {
        return STATUS_UNSUPPORTED; /* For now, only TIM2 */
    }
    
    if (config->frequency == 0 || config->frequency > timer_clk) {
        return STATUS_INVALID_PARAM;
    }
    
    uint32_t psc = (timer_clk / config->frequency) - 1;
    tim->PSC = psc;
    
    /* 3. Configure Mode */
    tim->CR1 = 0; /* Reset CR1 */
    if (config->mode == TIMER_MODE_ONE_SHOT) {
        tim->CR1 |= TIM_CR1_OPM; /* One-Pulse Mode */
    }
    
    /* Enable auto-reload preload */
    tim->CR1 |= TIM_CR1_ARPE;
    
    /* 4. Configure Callback */
    if (tim == TIM2) {
        tim2_callback = config->callback;
        tim2_callback_arg = config->callback_arg;
        nvic_enable_irq(28); /* TIM2_IRQn is 28 */
    }
    
    /* Enable Update Interrupt */
    tim->DIER |= TIM_DIER_UIE;
    
    return STATUS_OK;
}

status_t timer_set_period(TIM_TypeDef *timer, uint32_t us)
{
    if (!timer || us == 0) return STATUS_INVALID_PARAM;
    
    /* ARR defines the period */
    timer->ARR = us - 1;
    
    /* Generate an update event to immediately apply PSC and ARR */
    timer->EGR |= TIM_EGR_UG;
    
    /* Clear the update flag generated by UG to prevent false interrupt */
    timer->SR &= ~TIM_SR_UIF;
    
    return STATUS_OK;
}

status_t timer_start(TIM_TypeDef *timer)
{
    if (!timer) return STATUS_INVALID_PARAM;
    timer->CR1 |= TIM_CR1_CEN;
    return STATUS_OK;
}

status_t timer_stop(TIM_TypeDef *timer)
{
    if (!timer) return STATUS_INVALID_PARAM;
    timer->CR1 &= ~TIM_CR1_CEN;
    /* Also clear interrupt flag just in case */
    timer->SR &= ~TIM_SR_UIF;
    return STATUS_OK;
}

void TIM2_IRQHandler(void)
{
    if (TIM2->SR & TIM_SR_UIF) {
        /* Clear the interrupt flag */
        TIM2->SR &= ~TIM_SR_UIF;
        
        /* Execute callback */
        if (tim2_callback) {
            tim2_callback(tim2_callback_arg);
        }
    }
}
